### ISSUE TITLE
Deploying Bug

### ISSUE THREAD

**Issue by niclaskato** [issaafalkattan/react-landing-page-template-2021#12]
When delaying this project from Vercel, I am faced in building errors.

**Comment by tolgadur** [comment]
I am facing the same issue 
```
Failed to compile.
--
16:16:59.851 |  
16:16:59.852 | HookWebpackError: error:0308010C:digital envelope routines::unsupported
16:16:59.852 | at makeWebpackError (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:45539:9)
16:16:59.852 | at /vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:29467:12
16:16:59.852 | at eval (eval at create (/vercel/path0/node_modules/next/dist/compiled/webpack/bundle5.js:140927:10), <anonymous>:91:1)
16:16:59.852 | -- inner error --
16:16:59.853 | Error: error:0308010C:digital envelope routines::unsupported
16:16:59.853 | at new Hash (node:internal/crypto/hash:71:19)
16:16:59.853 | at Object.createHash (node:crypto:133:10)
16:16:59.854 | at getHashDigest (/vercel/path0/node_modules/next/dist/compiled/loader-utils/index.js:1:29141)
16:16:59.854 | at /vercel/path0/node_modules/next/dist/compiled/loader-utils/index.js:1:31472
16:16:59.854 | at String.replace (<anonymous>)
16:16:59.855 | at Object.interpolateName (/vercel/path0/node_modules/next/dist/compiled/loader-utils/index.js:1:31381)
16:16:59.855 | at /vercel/path0/node_modules/next/dist/build/webpack/plugins/copy-file-plugin.js:41:51
```

**Comment by wahyunandanovan** [comment]
i tried to deploy on netlify and the problem is solved

**Comment by abdelrahman-essawy** [comment]
I occurred this problem when trying to deploy on [Vercel](https://vercel.com), here is how I solved it:
- Downgrading to Node.js v16.
- Overriding build command to ```npm run build-prod```.
- Overriding Output Directory to ```out```
- Overriding Install command to ```npm run install```
